### ISSUE TITLE
markdown linting

### ISSUE THREAD

**Issue by olix0r** [linkerd/rfc#22]
Wanted: a markdown-linting script that enforce consistent document formatting. Should be a merge-check and a tool that can be run manually to check/fix.

Also, I think we should ideally enforce an 80 char wrap...

**Comment by admc** [comment]
Maybe https://github.com/marketplace/actions/markdown-linting-action will do what we want?

**Comment by ihcsim** [comment]
@kleimkuhler Is there anything else left on this one?

**Comment by kleimkuhler** [comment]
@ihcsim Nope! This was covered in linkerd/linkerd2#4402 and linkerd/rfc#28
