### ISSUE TITLE
Question: Link to Linkerd's scope

### ISSUE THREAD

**Issue by leecalcote** [linkerd/rfc#37]
Does Linkerd have a published project scope? How is an RFC identified as in or out of scope?

**Comment by wmorgan** [comment]
We have things like https://linkerd.io/design-principles/ which answer some of this, but not necessarily at the level of specific features. I'm not against this per se, but Lee do you have examples of other projects that do this, that you like?

**Comment by leecalcote** [comment]
This scratches the itch. Much appreciated, Mr. Morgan!
